import type { Metadata } from "next"
import { PageHeader } from "@/components/shared/PageHeader"
import { Pagination } from "@/components/shared/Pagination"
import { VocabularyListManager } from "@/components/vocabulary/VocabularyListManager"
import { parsePositivePage, buildUrl } from "@/lib/courses/query"
import { getVocabulary } from "@/lib/vocabulary/server"

export const metadata: Metadata = { title: "My vocabulary" }
export default async function Page({ searchParams }: { searchParams: Promise<{ page?: string; filter?: string }> }) { const params = await searchParams; const page = parsePositivePage(params.page); const filter = params.filter === "review" ? "review" : params.filter === "stable" ? "stable" : "all"; const needs = filter === "review" ? true : filter === "stable" ? false : undefined; const data = await getVocabulary(page, buildUrl("/my-vocabulary", { page, filter: filter === "all" ? undefined : filter }), needs); return <div className="mx-auto max-w-5xl px-4 py-9 sm:px-6"><PageHeader title="My vocabulary" description="Every item is a learned dictionary sense. Manage review status or remove senses from your learned vocabulary." /><div className="mt-6 flex gap-2 text-sm">{["all","review","stable"].map((value) => <a key={value} href={value === "all" ? "/my-vocabulary" : `/my-vocabulary?filter=${value}`} className={`rounded-full border px-3 py-1.5 ${filter === value ? "bg-primary text-primary-foreground" : "bg-background"}`}>{value === "all" ? "All" : value === "review" ? "Needs review" : "Review off"}</a>)}</div><div className="mt-6"><VocabularyListManager rows={data.results} actions={[{ action: "set_needs_review", label: "Add to review" }, { action: "unset_needs_review", label: "Remove from review" }, { action: "unset_learned", label: "Remove learned status", variant: "destructive" }]} /></div><Pagination page={page} count={data.count} makeHref={(next) => buildUrl("/my-vocabulary", { page: next, filter: filter === "all" ? undefined : filter })} /></div> }
