"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { LoaderCircle } from "lucide-react"
import { ApiErrorMessage } from "@/components/shared/ApiErrorMessage"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { apiClient } from "@/lib/api/client"
import type { SectionFlat } from "@/types/api/courses"

export function SectionCreateForm({ courseId, defaultOrder }: { courseId: number; defaultOrder: number }) { const router = useRouter(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); form.set("course", String(courseId)); form.set("is_published", form.get("is_published") === "on" ? "true" : "false"); setBusy(true); setError(null); try { const section = await apiClient.post<SectionFlat, FormData>("/api/courses/sections/", form); router.push(`/admin/courses/${courseId}/sections/${section.id}`); router.refresh() } catch (caught) { setError(caught) } finally { setBusy(false) } } if (!open) return <Button onClick={() => setOpen(true)}>Add section</Button>; return <div className="w-full rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">New section</h3><Button variant="ghost" size="sm" onClick={() => setOpen(false)}>Cancel</Button></div><form onSubmit={submit} className="mt-4 grid gap-4"><ApiErrorMessage error={error} /><div className="grid gap-4 sm:grid-cols-[1fr_120px]"><div className="space-y-2"><Label htmlFor="new_section_title">Title</Label><Input id="new_section_title" name="title" required /></div><div className="space-y-2"><Label htmlFor="new_section_order">Order</Label><Input id="new_section_order" name="order" type="number" min={0} defaultValue={defaultOrder} required /></div></div><div className="space-y-2"><Label htmlFor="new_video_url">Video URL</Label><Input id="new_video_url" name="video_url" type="url" required placeholder="https://…" /><p className="text-xs text-muted-foreground">For a Next.js public file during development, use an absolute URL such as http://localhost:3000/videos/demo.mp4.</p></div><div className="space-y-2"><Label htmlFor="new_subtitle">WebVTT subtitle file</Label><Input id="new_subtitle" name="subtitle_file" type="file" accept=".vtt,text/vtt" required /></div><label className="flex items-center gap-2 text-sm"><input className="size-4" type="checkbox" name="is_published" /> Published</label><Button disabled={busy}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : null}{busy ? "Creating…" : "Create section"}</Button></form></div> }
