"use client"

import { useState } from "react"
import { Volume2 } from "lucide-react"
import { DeleteButton } from "@/components/admin/DeleteButton"
import { EntryForm } from "@/components/admin/dictionary/EntryForm"
import { SenseForm } from "@/components/admin/dictionary/SenseForm"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import type { Entry } from "@/types/api/dictionary"

export function DictionaryEntryCard({ entry }: { entry: Entry }) { const [editing, setEditing] = useState(false); const [addingSense, setAddingSense] = useState(false); return <article className="rounded-xl border bg-card"><div className="flex flex-wrap items-start gap-4 border-b p-5"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">{entry.word}</h2><Badge variant="outline">{entry.part_of_speech}</Badge>{entry.register ? <Badge variant="secondary">{entry.register}</Badge> : null}</div>{entry.pronunciation?.text ? <p className="mt-2 text-sm text-muted-foreground">{entry.pronunciation.text}</p> : null}<PronunciationAudio pronunciation={entry.pronunciation} /></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing((v) => !v)}>{editing ? "Close edit" : "Edit entry"}</Button><DeleteButton endpoint={`/api/dictionary/entries/${entry.id}/`} confirmation={`Delete “${entry.word}” and all of its senses? Django will block this if a sense is used in a course mapping.`} /></div></div>{editing ? <div className="border-b p-5"><EntryForm entry={entry} onDone={() => setEditing(false)} /></div> : null}<div className="divide-y">{entry.senses.map((sense) => <details key={sense.id} className="group"><summary className="cursor-pointer list-none p-5"><div className="flex items-start gap-3"><span className="mt-0.5 text-xs text-muted-foreground">{sense.sense_number || "—"}</span><div className="min-w-0 flex-1"><p className="font-medium">{sense.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{sense.definition}</p></div></div></summary><div className="border-t bg-muted/10 p-5"><div className="mb-4 flex justify-end"><DeleteButton endpoint={`/api/dictionary/senses/${sense.id}/`} confirmation={`Delete sense “${sense.title}”? Django will block this if it is used in a course mapping.`} label="Delete sense" /></div><SenseForm entryId={entry.id} sense={sense} /></div></details>)}</div><div className="border-t p-5">{addingSense ? <><div className="mb-4 flex justify-between"><h3 className="font-semibold">New sense</h3><Button variant="ghost" size="sm" onClick={() => setAddingSense(false)}>Cancel</Button></div><SenseForm entryId={entry.id} onDone={() => setAddingSense(false)} /></> : <Button variant="outline" onClick={() => setAddingSense(true)}>Add sense</Button>}</div></article> }
function PronunciationAudio({ pronunciation }: { pronunciation: Entry["pronunciation"] }) { const urls = [{ label: "British", url: pronunciation?.br_audio }, { label: "American", url: pronunciation?.am_audio }].filter((item): item is { label: string; url: string } => Boolean(item.url)); if (!urls.length) return null; return <div className="mt-3 flex flex-wrap gap-2">{urls.map((item) => <button key={item.label} type="button" className="inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-xs" onClick={() => void new window.Audio(item.url).play()}><Volume2 className="size-3" />{item.label}</button>)}</div> }
