# Generated by Django 5.2.16 on 2026-08-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_known', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by', to='dictionary.sense')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
