# Generated by Django 5.2.16 on 2026-08-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField(max_length=1000)),
                ('subtitle_file', models.FileField(upload_to='section_subtitles/')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ['course_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WordSenseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_sense_mappings', to='courses.section')),
                ('senses', models.ManyToManyField(related_name='word_mappings', to='dictionary.sense')),
            ],
            options={
                'ordering': ['section_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('cue_id', models.PositiveIntegerField()),
                ('cue_start_time', models.FloatField()),
                ('cue_end_time', models.FloatField()),
                ('previous_cue_start_time', models.FloatField(blank=True, null=True)),
                ('previous_cue_end_time', models.FloatField(blank=True, null=True)),
                ('next_cue_start_time', models.FloatField(blank=True, null=True)),
                ('next_cue_end_time', models.FloatField(blank=True, null=True)),
                ('position_in_cue', models.PositiveIntegerField()),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_words', to='courses.wordsensemapping')),
            ],
            options={
                'ordering': ['mapping_id', 'cue_id', 'position_in_cue', 'id'],
                'indexes': [models.Index(fields=['mapping', 'cue_id', 'position_in_cue'], name='courses_sub_mapping_4e52fb_idx')],
            },
        ),
    ]
