# Generated by Django 5.2.16 on 2026-08-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('part_of_speech', models.CharField(db_index=True, max_length=100)),
                ('pronunciation', models.JSONField(blank=True, null=True)),
                ('frequency', models.JSONField(blank=True, default=list)),
                ('inflections', models.TextField(blank=True, null=True)),
                ('register', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['word', 'part_of_speech', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_number', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
                ('lex_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('geo', models.CharField(blank=True, max_length=100, null=True)),
                ('register', models.CharField(blank=True, max_length=100, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('opposites', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='dictionary.entry')),
            ],
            options={
                'ordering': ['entry__word', 'entry_id', 'sense_number', 'id'],
            },
        ),
    ]
