# Generated by Django 5.2.16 on 2026-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_entry_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sense',
            name='sense_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
