# Generated by Django 5.2.16 on 2026-09-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_entry_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
